config/routes.rb
PomoGame::Application.routes.draw do
  root 'welcome#index'
  
  resources :users
  resources :high_scores, only: :index
  
  delete "sign_out", to: "sessions#destroy", as: "sign_out"
  resources :sessions, only: [:create, :new]

  

end

app/models/high_score.rb
class HighScore < ActiveRecord::Base
  belongs_to :user
  
  validates :user, presence: true
  validates :score, presence: true
  
  def to_s
    "#{user} scored: #{score}!"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :high_scores
  
  validates :username, presence: true, uniqueness: true
  validates :password, presence: true, confirmation: true
  
  def to_s
    username
  end
  
  def can_play
    if last_played 
      last_played + 15.minutes < DateTime.now
    else
      true
    end
  end
  
  def play_time
    time = last_played + 15.minutes
    time.strftime("%l:%M %p")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  private
  
  helper_method :current_user
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/high_scores_controller.rb
class HighScoresController < ApplicationController
  def index
    @scores = HighScore.all
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(username: params[:username])
    
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:notice] = "You have signed in!"
      redirect_to user
    else
      flash.now[:alert] = "Invalid username or password"
      redirect_to :back
    end
  end
  
  def destroy
    flash[:notice] = "You have signed out"
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: 'User was successfully created.'
    else
      flash[:alert] = "Error in account creation"
      render "welcome/index"
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to root_path }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @user = User.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/high_scores_helper.rb
module HighScoresHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/high_scores/index.html.erb
<% @scores.each do |score| %>
  <h2><%= score %></h2>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PomoGame</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  
  <script type="text/javascript">
    $(document).ready(function(){
      $(".scroll-area").scrollspy({target: "#Navbar"}) 
    });
  </script>
  
</head>
<body>
  <div class="container-fluid">
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-main">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "Pomodori", root_path, class: "navbar-brand", style: "padding-left:100px;"%>
        </div>

        <div class="collapse navbar-collapse" id="navbar-collapse-main">
          <ul class="nav nav-tabs navbar-right" style="margin: 10px 80px 0px 0px">
            <li><%= link_to "Main", root_path %></li>
            <% if current_user %>
            <li><%= link_to current_user, current_user %></li>
            <li><%= link_to "High Scores", high_scores_path %></li>
            <li><%= link_to "Log out", sign_out_path, method: :delete %></li>
            <% else %>
            <li><a href="#sign">Sign up</a></li>
            <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
    <%= yield %>
  </div>
</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice" style="margin-top: 20px;"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user %>
</p>

<p>
  <strong>Score:</strong>
  <%= @user.score %>
</p>

<% if @user.can_play %>
  <p>Have Fun</p>
          <div class="row" style=" padding-top:80px;">
            <div class="col-sm-12 text-center">
                
                <!--canvas for putting images-->
                <!--Loading all possible images-->
              <%= image_tag "dragon.png", class: "hide", id: "Dragon" %>
              <%= image_tag "BlackEyes.png", class: "hide", id: "BlackEyes" %>
              <%= image_tag "Blob.png", class: "hide", id: "Blob" %>
              <%= image_tag "buleArrow.png", class: "hide", id: "BuleArrow" %>
              <%= image_tag "elephant.png", class: "hide", id: "Elephant" %>
              <%= image_tag "Fire.png", class: "hide", id: "Fire" %>
              <%= image_tag "FlyingCastle.png", class: "hide", id: "FlyingCastle" %>
              <%= image_tag "hatWacker.png", class: "hide", id: "HatWacker" %>
              <%= image_tag "monster.png", class: "hide", id: "Monster" %>
              <%= image_tag "monsterCookie.png", class: "hide", id: "MonsterCookie" %>
              <%= image_tag "noMoreSmile.png", class: "hide", id: "NoMoreSmile" %>
              <%= image_tag "stoneWall.png", class: "hide", id: "StoneWall" %>
              <%= image_tag "textBox.png", class: "hide", id: "TextBox" %>
              <%= image_tag "TurtlePickle.png", class: "hide", id: "TurtlePickle" %>
              <%= image_tag "Player1.png", class: "hide", id: "Player1" %>
              <%= image_tag "Player2.png", class: "hide", id: "Player2" %>
                <!--END IMAGE DUMP-->
                
                
                
                <canvas id="myCanvas" width="800" height="600" style="border:1px solid #d3d3d3; background-color: white"> </canvas>
                <script>
                    window.onload = function()
                    {
                        //Beginning of the game
                        //create the players
                        var player1 = new player("player1.png","Player1",5,2,50);
                        document.getElementById("hp1").innerHTML = "HP: " + player1.health + "/" + player1.maxHealth ;
                        var player2 = new player("player2.png","Player2",5,2,50);
                        document.getElementById("hp2").innerHTML = "HP: " + player2.health + "/" + player2.maxHealth ;
                        //Draw the Canvas and players
                        var c=document.getElementById("myCanvas");
                        var ctx=c.getContext("2d");
                        var img2=document.getElementById("Player1");
                        var img3=document.getElementById("Player2");
                        ctx.drawImage(img2,20,460);
                        ctx.drawImage(img3,660,460);

                        
                        //START OF AN ENCOUNTER
                        var encounter = Math.floor((Math.random()*14));
                        switch (encounter) {
                            case 0:
                                var Enemy = new enemy("BlackEyes.png","BlackEyes",8,1,17);
                                break;
                            case 1:
                                var Enemy = new enemy("Blob.png","Blob",2,1,49);
                                break;
                            case 2:
                                var Enemy = new enemy("buleArrow.png", "BuleArrow",5,2,20);
                                break;
                            case 3:
                                var Enemy = new enemy("Dragon.png","Dragon",7,4,40);
                                break;
                            case 4:
                                var Enemy = new enemy("Elephant.png","Elephant",3,2,28);
                                break;
                            case 5:
                                var Enemy = new enemy("Fire.png","Fire",10,0,8);
                                break;
                            case 6:
                                var Enemy = new enemy("FlyingCastle.png","FlyingCastle",3,3,36);
                                break;
                            case 7:
                                var Enemy = new enemy("hatWacker.png","HatWacker",2,2,22);
                                break;
                            case 8:
                                var Enemy = new enemy("monster.png","Monster",3,1,31);
                                break;
                            case 9:
                                var Enemy = new enemy("monstercookie.png","MonsterCookie",2,1,25);
                                break;
                            case 10:
                                var Enemy = new enemy("noMoreSmile.png","NoMoreSmile",6,3,42);
                                break;
                            case 11:
                                var Enemy = new enemy("StoneWall.png","StoneWall",1,5,53);
                                break;
                            case 12:
                                var Enemy = new enemy("textbox.png","TextBox",0,0,100);
                                break;
                            case 13:
                                var Enemy = new enemy("turtlepickle.png","TurtlePickle",4,2,35);
                                break;
                        }
                    
                        var img=document.getElementById(Enemy.name);
                        ctx.drawImage(img,270,140);
                        game_log("A wild " + Enemy.name + " has appeared to fight you!")
                        
                    }
                        
                </script>   
                <br>
 
            </div>
        </div> <!--ROW 1-->
        
        
        <div class="row" style=" border:1px solid #d3d3d3; height:100px;">
                 
                <div class="col-sm-1"></div>
                <div class="col-sm-2">
                    <h5 id="hp1" style="background-image: url(<%= asset_path 'healthBar.png' %>); width:103px; height:21px ">  </h5>
                  <%= image_tag "manaBar.png" %>
                </div>
                <div class="col-sm-1" align="left" style="padding:0px;"> <button type="button" onclick="getAttacked()"> -Attack- </button> <button type="button" onclick="">Inventory</button> </div>
                <div class="col-sm-4"></div>
                <div class="col-sm-1" align="left" style="padding:0px;"> <button type="button" onclick="getAttacked()"> -Attack- </button> <button type="button" onclick="">Inventory</button> </div>
                <div class="col-sm-2"> 
                    <h5 id="hp2" style="background-image: url(<%= asset_path 'healthBar.png' %>); width:103px; height:21px ">  </h5>
                  <%= image_tag "manaBar.png" %>                 
                </div>
                <div class="col-sm-1"></div>
        </div>
        
        
        <div class="row">
            <div class="col-sm-12 text-center" style="padding: 20px 50px; border:1px solid #d3d3d3;">
                <div id = "game-log" style="border:1px solid #d3d3d3; height: 160px; width: 800px;" align="center"> 
                    <h1>The Game log</h1>
                </div>
            </div>
        </div>
        
        
        
        
    </div> <!--Container fluid-->
  </body>

<!--JAVA SCRIPT FUNCTION DUMP-->
<script>
    var log = $("#game-log");

    function game_log(txt) {
        var message = "<h4>" + txt + "</h4>";
        log.append(message);
    }

    function getAttacked() {
    //document.getElementById("log").innerHTML = "You were attacked" ;
    }




    function player(image,name,weapon,armor,health) {  
        var invPressed = false;
        this.name = name;
        this.weapon = weapon;
        this.armor = armor;
        this.Str = Math.floor((Math.random()*6)+3);
        this.Skl = Math.floor((Math.random()*6)+3);
        this.Ini = Math.floor((Math.random()*6)+3);
        this.Dex = Math.floor((Math.random()*6)+3);
        this.Int = Math.floor((Math.random()*6)+3);
        this.Spr = Math.floor((Math.random()*6)+3);
        this.Tgh = Math.floor((Math.random()*6)+3);
        this.Lck = Math.floor((Math.random()*10)); 
        this.defense = (Math.floor(this.Tgh/2) + this.armor);
        this.attack = this.Str + this.weapon;
        this.health = health + this.Tgh;
        this.maxHealth = this.health;
        this.alive = true;    
    }
    
    function enemy(image,name,weapon,armor,health) {  
        var invPressed = false;
        this.name = name;
        this.weapon = weapon;
        this.armor = armor;
        this.Str = Math.floor((Math.random()*6)+3);
        this.Skl = Math.floor((Math.random()*6)+3);
        this.Ini = Math.floor((Math.random()*6)+3);
        this.Dex = Math.floor((Math.random()*6)+3);
        this.Int = Math.floor((Math.random()*6)+3);
        this.Spr = Math.floor((Math.random()*6)+3);
        this.Tgh = Math.floor((Math.random()*6)+3);
        this.Lck = Math.floor((Math.random()*10)); 
        this.defense = (Math.floor(this.Tgh/2) + this.armor);
        this.attack = this.Str + this.weapon;
        this.health = health + this.Tgh;
        this.maxHealth = this.health;
        this.alive = true;    
    }
    
    function updateHealth(target, num){
        if (target.health <= 0)
        {
            target.health = 0;
            target.alive = false;
        }
        else
        {
            target.health -= num;
            if (target.name == "Player1")
            {
                document.getElementById("hp1").innerHTML = "HP: " + target.health + "/" + target.maxHealth ;
                game_log("Player1 was hit for " + num + " damage!");
            }
            else if (target.name == "Player2")
            {
                document.getElementById("hp2").innerHTML = "HP: " + target.health + "/" + target.maxHealth ;
                game_log("Player2 was hit for " + num + " damage!");
            }
            else
                document.getElementById("hp3").innerHTML = "HP: " + target.health + "/" + target.maxHealth ;     
        }
    }
    
    
    
</script>

<% else %>
<p>You must wait until <%= @user.play_time %> to play</p>
<% end %>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>
<%= link_to 'Delete Account', @user, method: :delete, data: {message: "Are you sure you want to leave?"} %>

app/views/welcome/index.html.erb
            <!--FIRST SECTION-->
        <a name="main"></a>
        <div class="row" style=" padding-top:60px;">
            <div class="col-sm-1"> </div>
            <div class="col-sm-10 text-center"> 
                    <h1> <strong>WORK</strong> hard  | <strong>PLAY</strong> harder</h1>
                    <p>---</p>
                    <p>Have you ever wanted to <strong> actually </strong>get your work done, but also get in some quality gaming time?</p>
                    <p>---</p>
                    <p>Not very good at pacing yourself?</p>
                    <p>---</p>
                    <p> Need a way to balance studying and gaming?</p>
                    <p>---</p>
                    <h1> <strong>Try Pomodori!</strong> </h1>
            </div>
            <div class="col-sm-1"> </div>
        </div> <!--ROW 1-->
        
        
        
        <!--SECOND SECTION-->
        <a name="about"></a>
        <div class="row">
            <div class="col-sm-1"> </div>
            <div class="col-sm-10 text-center"> 
                <div class="page-header text-center">
                    <h1><strong>Pomo - What? </strong></h1>
                </div>
                <p>---</p>
                <p> This website is based off of the <strong>Pomodoro Technique </strong> which is a time management method developed by Francesco Cirillo in the late 1980s. The technique uses a timer to break down work into intervals traditionally 25 minutes in length, separated by short breaks. These intervals are known as "<strong>pomodori</strong>", the plural of the Italian word pomodoro for "tomato".  </p>
                <p>---</p>
                <p> The idea is that for each successive interval of work, you get a timed game break before you head back to work.  </p>
                <p> HOWEVER </p>
                <p> For every successive interval of work you accomplish, the reward multipliyer in game increases.</p>
                <p>---</p>
                <p>The longer you keep your work habit, the better the rewards!</p>
                
            </div>
            <div class="col-sm-1"> </div>
        </div> <!--ROW 2-->
        
        <!--THIRD SECTION-->
        <a name="sign"></a>
        <div class="row">
            <div class="col-sm-1"> </div>
            <div class="col-sm-10 text-center"> 
                <h1>Sign up now!</h1>
                
              <%= render "users/form" %>
                <p> Already have an account? </p>
                <%= form_tag sessions_path do %>
                  <h1>Sign in!</h1>
                  <div>
                    <%= label_tag :username %>
                    <%= text_field_tag :username, nil %>
                  </div>

                  <div>
                    <%= label_tag :password %>
                    <%= password_field_tag :password, nil %>
                  </div>

                  <%= submit_tag "Sign in" %>
                <% end %>
            </div>
            <div class="col-sm-1"> </div>
        </div> <!--ROW 1-->
        <!--ROW 3-->